apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: ecommerce
data:
  mysql.cnf: |
    [mysqld]
    max_connections=200
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci