apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ecommerce
type: Opaque
data:
  # Base64 encoded values
  # root-password: echo -n 'MyRootPass123!' | base64
  root-password: TXlSb290UGFzczEyMyE=
  # database: echo -n 'ecommerce' | base64
  database: ZWNvbW1lcmNl
  # user: echo -n 'ecomuser' | base64
  user: ZWNvbXVzZXI=
  # password: echo -n 'EcomPass123!' | base64
  password: RWNvbVBhc3MxMjMh